name: "Report Coverage"
description: "Creates a coverage report"
inputs:
  threshold:
    description: "Minimum proportion of modified lines that need to be covered for acceptance or -1 if there is no minimum."
    required: false
    default: "-1"

runs:
  using: "composite"
  steps:
    - name: Install LLVM tools
      shell: bash
      run: rustup component add llvm-tools-preview
    - name: Install grcov
      shell: bash
      run: cargo install grcov
    - name: Collect coverage profiles
      shell: bash
      run: |
        zip -0 raw_cov.zip $(find . -name "*.profraw") -q
        rm $(find -name '*.profraw')
    # Note: source-based branch coverage is not supported for Rust
    # (see http://github.com/rust-lang/rust/issues/79649)
    - name: Build coverage report
      shell: bash
      run: |
        mkdir -p ./target/coverage
        grcov raw_cov.zip \
            --source-dir . \
            --binary-path ./target/debug/ \
            -t markdown,html,cobertura \
            --ignore 'target/debug/*' \
            --ignore "/*" \
            --ignore-not-existing \
            -o ./target/coverage/
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: coverage_report
        path: target/coverage/html/
        retention-days: 30
    - name: Collect results
      shell: bash
      env:
        ISSUE_NUMBER: ${{ github.event.number }}
        REPORT_LOCATION: ${{ steps.upload-artifact.outputs.artifact-url }}
      run: |
        mkdir -p target/coverage/results
        echo "FAILED" >> target/coverage/results/status.txt
        mv target/coverage/markdown.md target/coverage/results/
        echo $ISSUE_NUMBER >> target/coverage/results/issue_number.txt
        echo $REPORT_LOCATION >> target/coverage/results/report_location.txt
        echo $THRESHOLD >> target/coverage/results/threshold.txt
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: coverage_results
        path: target/coverage/results/
        retention-days: 1