name: Comment on the pull request

on:
  workflow_run:
    workflows: [Cargo Build & Test]
    types:
      - completed

jobs:
  printJob:    
      name: Print event
      runs-on: ubuntu-latest
      steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Download archives
        shell: bash
        run: gh run download $RUN_ID
        env:
          RUN_ID: ${{github.event.workflow_run.id }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('./NR'));
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: 'Everything is OK. Thank you for the PR!'
            });
      - name: Set status
        shell: bash
        run: echo "hello"
      - name: Add comment to PR
        shell: bash
        run: gh pr comment $PR --body-file markdown.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.workflow_run.url }}
      - name: Report failures
        if: ${{ env.STATUS == 'FAILED' }}
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('Coverage of modified lines was below threshold.')
